WebApplication/Controllers/DeliveryManController.cs
using BLL;
using DTO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class DeliveryManController : Controller
    {
        private IDeliveryManManager DeliveryManManager;
        private IDeliveryOrderListManager DeliveryOrderListManager;
        private IOrderManager OrderManager;
        private IOrderDishesManager OrderDishesManager;
        private IDishesManager DishesManager;
        private IRestaurantDishesManager RestaurantDishesManager;
        private IRestaurantManager RestaurantManager;
        private ILocationManager LocationManager;
        private IPersonManager PersonManager;

        public DeliveryManController(IDeliveryManManager deliveryManManager, IDeliveryOrderListManager deliveryOrderListManager, IOrderManager orderManager, IOrderDishesManager orderDishesManager, IDishesManager dishesManager, IRestaurantDishesManager restaurantDishesManager, IRestaurantManager restaurantManager, ILocationManager locationManager, IPersonManager personManager)
        {
            DeliveryManManager = deliveryManManager;
            DeliveryOrderListManager = deliveryOrderListManager;
            OrderManager = orderManager;
            OrderDishesManager = orderDishesManager;
            DishesManager = dishesManager;
            RestaurantDishesManager = restaurantDishesManager;
            RestaurantManager = restaurantManager;
            LocationManager = locationManager;
            PersonManager = personManager;
        }
        // GET: DeliveryManController
        public ActionResult Index()
        {
            //verifie que le livreur est bien connecte
            if (HttpContext.Session.GetInt32("IdDeliveryMan") == null)
            {
                    return RedirectToAction("Index", "Login");
            }
            //va chercher son id
            var id = (int) HttpContext.Session.GetInt32("IdDeliveryMan");
            //va chercher toutes ses informations
            var deliveryMan = DeliveryManManager.GetDeliveryManID(id);

            var statusVM = new StatusVM();
            statusVM.deliveryStatut = deliveryMan.IsWorking;
            //va chercher toute les deliveryOrderList lien a ce livreur
            var deliveryOrders = DeliveryOrderListManager.GetDeliveryOrderList(id);
            //regarde s'il a des commandes
            if (deliveryOrders != null) {
            List<Order> orders = new List<Order>();
            List<int> status = new List<int>();
            //prend toutes ses commandes est numero de statut
            foreach (var deliveryOrder in deliveryOrders)
            {
                var order = OrderManager.GetOrderIDOrder(deliveryOrder.ID_Order);
                orders.Add(order);
                status.Add(deliveryOrder.NumStatut);
            }
            statusVM.orders = orders;
            statusVM.status = status;
            }

            return View("Index",statusVM);
        }

        // GET: DeliveryManController/Details/5
        public ActionResult Detail(int id)
        {
            //verifie que le livreur est bien connecte
            if (HttpContext.Session.GetInt32("IdDeliveryMan") == null)
            {
                return RedirectToAction("Index", "Login");
            }

            DeliveryOrderDetailVM final = new DeliveryOrderDetailVM();
            List<string> DishesName = new List<string>();
            List<int> Quantity = new List<int>();
            List<string> RestaurantName = new List<string>();
            List<string> RestaurantAddress = new List<string>();
            List<int> RestaurantNPA = new List<int>();
            List<string> RestaurantsCity = new List<string>();

            //va chercher la commande correspondante a l'id donne
            Order order = OrderManager.GetOrderIDOrder(id);
            //va chercher les orderDishes correspondantes
            var orderDishes = OrderDishesManager.GetOrderDishes(id);
            foreach(var orderDish in orderDishes)
            {
                var dish = DishesManager.GetDishIP(orderDish.ID_Dishes);
                Quantity.Add(orderDish.Quantity);
                DishesName.Add(dish.DishesName);

                var restaurantDish = RestaurantDishesManager.GetRestaurant(dish.ID_Dishes);
                var restaurant = RestaurantManager.GetRestaurantID(restaurantDish.ID_restaurant);
                RestaurantName.Add(restaurant.RestaurantName);
                RestaurantAddress.Add(restaurant.RestaurantAddress);

                var location = LocationManager.GetLocationID(restaurant.ID_location);
                RestaurantNPA.Add(location.NPA);
                RestaurantsCity.Add(location.City);
            }

            //va chercher la person
            var person = PersonManager.GetPersonID(order.ID_person);
            var locationPerson = LocationManager.GetLocationID(person.ID_location);
            var deliveryOrder = DeliveryOrderListManager.GetDeliveryFromOrder(id);

            //mes toutes les informations dans le model
            final.clientAdress = person.Address;
            final.clientCity = locationPerson.City;
            final.clientFirstName = person.FirstName;
            final.clientName = person.Name;
            final.clientTel = person.PhoneNumber;
            final.clientNPA = locationPerson.NPA;
            final.DishesName = DishesName;
            final.NumStatut = deliveryOrder.NumStatut;
            final.Quantity = Quantity;
            final.RestaurantAddress = RestaurantAddress;
            final.RestaurantName = RestaurantName;
            final.RestaurantNPA = RestaurantNPA;
            final.RestaurantsCity = RestaurantsCity;

            int total = 0;
            //va chercher les plats
            var dishes = OrderManager.GetDishesFromOrder(id);
            //va chercher le montant que doit le client
            for (int i=0; i<Quantity.Count; i++)
            {
                int sousTotal = dishes[i].DishesPrice * Quantity[i];
                total += sousTotal;
            }
            final.clientPrixTotal = total;

            //verifie qu'il n'y a pas de idOrder dans la session
            if (HttpContext.Session.GetInt32("IdOrder") != null)
                HttpContext.Session.Remove("IdOrder");

            //ajoute idOrder dans la session
            HttpContext.Session.SetInt32("IdOrder", id);

            return View("Detail",final);
        }
        public ActionResult Begin()
        {
            //va chercher l'id de la commande
            int idOrder = (int)HttpContext.Session.GetInt32("IdOrder");
            var deliveryOrderList = DeliveryOrderListManager.GetDeliveryFromOrder(idOrder);
            //change le statut de la commande
            deliveryOrderList.NumStatut = 2;
            DeliveryOrderListManager.ModifyStatut(deliveryOrderList);

            return Detail(idOrder);
        }
        public ActionResult Finish()
        {
            //va chercher l'id de la commande
            int idOrder = (int)HttpContext.Session.GetInt32("IdOrder");
            var deliveryOrderList = DeliveryOrderListManager.GetDeliveryFromOrder(idOrder);
            //change le statut de la commande
            deliveryOrderList.NumStatut = 3;
            DeliveryOrderListManager.ModifyStatut(deliveryOrderList);

            return Index();
        }
        public ActionResult Active()
        {
            //va chercher l'id du livreur
            int id = (int)HttpContext.Session.GetInt32("IdDeliveryMan");
            //va changer son statut de travail
            DeliveryManManager.ChangeIsWorking(id, 1);

            return Index();
        }
        public ActionResult Desactive()
        {
            //va chercher l'id du livreur
            int id = (int)HttpContext.Session.GetInt32("IdDeliveryMan");
            //va changer son statut de travail
            DeliveryManManager.ChangeIsWorking(id,0);

            return Index();
        }


    }
}

WebApplication/Controllers/RestaurantsController.cs
using BLL;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication.Controllers
{
    public class RestaurantsController : Controller
    {
        private IRestaurantManager RestaurantManager;

        public RestaurantsController(IRestaurantManager restaurantManager)
        {
            RestaurantManager = restaurantManager;
        }
        // GET: RestaurantsController
        public ActionResult Index()
        {
            //verifie que la person ou le livreur est bien connecte
            if (HttpContext.Session.GetInt32("IdDeliveryMan") == null)
            {
                if (HttpContext.Session.GetInt32("IdPerson") == null)
                    return RedirectToAction("Index", "Login");
            }

            var restaurants = RestaurantManager.GetRestaurants();
            return View(restaurants);
        }

        // GET: RestaurantsController/Details/5
        public ActionResult Details(int id)
        {
            //verifie que la person ou le livreur est bien connecte
            if (HttpContext.Session.GetInt32("IdDeliveryMan") == null)
            {
                if (HttpContext.Session.GetInt32("IdPerson") == null)
                    return RedirectToAction("Index", "Login");
            }
            return View();
        }

        // GET: RestaurantsController/Create
        public ActionResult Create()
        {
            //verifie que la person ou le livreur est bien connecte
            if (HttpContext.Session.GetInt32("IdDeliveryMan") == null)
            {
                if (HttpContext.Session.GetInt32("IdPerson") == null)
                    return RedirectToAction("Index", "Login");
            }
            return View();
        }

        // POST: RestaurantsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            //verifie que la person ou le livreur est bien connecte
            if (HttpContext.Session.GetInt32("IdDeliveryMan") == null)
            {
                if (HttpContext.Session.GetInt32("IdPerson") == null)
                    return RedirectToAction("Index", "Login");
            }
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: RestaurantsController/Edit/5
        public ActionResult Edit(int id)
        {
            //verifie que la person ou le livreur est bien connecte
            if (HttpContext.Session.GetInt32("IdDeliveryMan") == null)
            {
                if (HttpContext.Session.GetInt32("IdPerson") == null)
                    return RedirectToAction("Index", "Login");
            }
            var restaurant = RestaurantManager.GetRestaurantID(id);
            return View(restaurant);
        }

        // POST: RestaurantsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(DTO.Restaurant r)
        {
            //verifie que la person ou le livreur est bien connecte
            if (HttpContext.Session.GetInt32("IdDeliveryMan") == null)
            {
                if (HttpContext.Session.GetInt32("IdPerson") == null)
                    return RedirectToAction("Index", "Login");
            }
            try
            {
                RestaurantManager.ModifyAllRestaurant(r);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(r);
            }
        }

        // GET: RestaurantsController/Delete/5
        public ActionResult Delete(int id)
        {
            //verifie que la person ou le livreur est bien connecte
            if (HttpContext.Session.GetInt32("IdDeliveryMan") == null)
            {
                if (HttpContext.Session.GetInt32("IdPerson") == null)
                    return RedirectToAction("Index", "Login");
            }
            return View();
        }

        // POST: RestaurantsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            //verifie que la person ou le livreur est bien connecte
            if (HttpContext.Session.GetInt32("IdDeliveryMan") == null)
            {
                if (HttpContext.Session.GetInt32("IdPerson") == null)
                    return RedirectToAction("Index", "Login");
            }
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

WebApplication/Controllers/StatusController.cs
using BLL;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class StatusController : Controller
    {
        private readonly ILogger<OrderController> _logger;
        private IOrderManager OrderManager;
        private IDeliveryOrderListManager DeliveryOrderListManager;
        private IOrderDishesManager OrderDishesManager;
        private IDishesManager DishesManager;
        private IDeliveryManManager DeliveryManManager;

        public StatusController(ILogger<OrderController> logger, IOrderManager orderManager, IDeliveryOrderListManager deliveryOrderListManager, IOrderDishesManager orderDishesManager, IDishesManager dishesManager, IDeliveryManManager deliveryManManager)
        {
            _logger = logger;
            OrderManager = orderManager;
            DeliveryOrderListManager = deliveryOrderListManager;
            OrderDishesManager = orderDishesManager;
            DishesManager = dishesManager;
            DeliveryManManager = deliveryManManager;
        }

        // GET: StatusController
        public ActionResult Index()
        {
            //verifie que la person est bien connecte
            if (HttpContext.Session.GetInt32("IdPerson") == null)
                return RedirectToAction("Index", "Login");

            //va chercher son id
            int idPerson = (int) HttpContext.Session.GetInt32("IdPerson");
            //va chercher ses informations
            var listOrders = OrderManager.GetOrderIDPerson(idPerson);
            List<int> listNumStatut = new List<int>();
            StatusVM status = new StatusVM();
            //verifie si la personne a deja commande quelque chose
            if (listOrders != null)
            {
                foreach (var order in listOrders)
                {
                    var deliveryOrderList = DeliveryOrderListManager.GetDeliveryFromOrder(order.ID_Order);
                    listNumStatut.Add(deliveryOrderList.NumStatut);
                }
                
                status.orders = listOrders;
                status.status = listNumStatut;
            }
            


            return View("Index",status) ;
        }

        // GET: StatusController/Details/5
        public ActionResult Detail(int id)
        {
            OrderVM order = new OrderVM();
            order.IdOrder = id;
            //va chercher les orderDishes correspondants a l'id
            var orderDishes = OrderDishesManager.GetOrderDishes(id);
            List<string> DishesName = new List<string>();
            List<int> DishesId = new List<int>();
            List<int> DishesUnitePrice = new List<int>();
            List<int> DishesTotalPrice = new List<int>();
            List<int> Quantity = new List<int>();
            int TotalPrice = 0;

            //Dish
            foreach (var orderDish in orderDishes)
            {
                var dish = DishesManager.GetDishIP(orderDish.ID_Dishes);
                DishesName.Add(dish.DishesName);
                DishesId.Add(dish.ID_Dishes);
                DishesUnitePrice.Add(dish.DishesPrice);
                Quantity.Add(orderDish.Quantity);
                DishesTotalPrice.Add(dish.DishesPrice * orderDish.Quantity);
            }

            foreach(var disheTotal in DishesTotalPrice)
            {
                TotalPrice += disheTotal;
            }

            order.DishesName = DishesName;
            order.DishesId = DishesId;
            order.DishesUnitePrice = DishesUnitePrice;
            order.Quantity = Quantity;
            order.DishesTotalPrice = DishesTotalPrice;
            order.TotalPrice = TotalPrice;

            //DeliveryMan
            var deliveryOrderList = DeliveryOrderListManager.GetDeliveryFromOrder(id);
            var deliveryMan = DeliveryManManager.GetDeliveryManID(deliveryOrderList.Id_Delivery);
            order.DeliveryManName = deliveryMan.NameDelivery;
            order.DeliveryManTel = deliveryMan.PhoneNumberDelivery;

            //Order
            var ord = OrderManager.GetOrderIDOrder(id);
            order.DelaiLivraison = ord.DelaiLivraison;

            return View(order);
        }

        public ActionResult Remove(int id)
        {
            //va chercher le deliveryOrderList
            var deliveryOrderList = DeliveryOrderListManager.GetDeliveryFromOrder(id);
            //change le statut de la commande en annule
            deliveryOrderList.NumStatut = 0;
            DeliveryOrderListManager.ModifyStatut(deliveryOrderList);

            return Index();
        }

        
    }
}

WebApplication/Views/Shared/_DeliveryManLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DeliveryManLayout</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="DeliveryMan" asp-action="Index"><img src="~/Images/HomePage/LogoWhite.png" alt="LogoWhite.png" width="110" height="28"/></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="AccountDeliveryMan">Compte</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
        
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApplication/Views/Shared/_IndexLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IndexLayout</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/Images/HomePage/LogoWhite.png" alt="LogoWhite.png" width="110" height="28"/></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/Images/HomePage/LogoWhite.png" alt="LogoWhite.png" width="110" height="28"/></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Restaurants" asp-action="Index">Restaurants</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Status" asp-action="Index">Mes Commandes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Account">Compte</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">Panier</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
        
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>